# Generated by Django 5.1.4 on 2025-01-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product_description', models.TextField(blank=True, max_length=500, null=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product/')),
            ],
        ),
    ]
