# Generated by Django 5.1.4 on 2025-01-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeldasApp', '0002_category_factory_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='fac_prize',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
